### ISSUE TITLE
A possible design for a built-in `=formula` and `F<>` mechanism

### ISSUE THREAD

**Issue by thoughtstream** [Raku/RakuDoc-GAMMA#12]
### A possible design for RakuDoc formulas

@zag has proposed adding support for formula specifications,
using `=formula` blocks and inline `F<>` instructions.

I admit that I am extremely taken with the idea of allowing proper formulas within RakuDoc,
but there are several significant issues that would need to be addressed before we could
seriously consider adding this feature to the specification.

The two main issues are:

1. There are far too many alternative markup notations that
   could be used within formula blocks/instructions:

    * [TeX/LaTeX](https://en.wikibooks.org/wiki/LaTeX/Mathematics)
    * [Typst](https://typst.app/docs/reference/math/)
    * [ASCIIMath](http://asciimath.org/)
    * [eqn](https://en.wikipedia.org/wiki/Eqn_(software))
    * [MathML](https://en.wikipedia.org/wiki/MathML)
    * [OpenMath](https://en.wikipedia.org/wiki/OpenMath)
    * [OMDoc](https://www.omdoc.org)

2. Whichever notation we chose _(or even invented),_ it is an extremely heavy burden to require
   all future RakuDoc renderers to render something as complex as mathematical notation
   across the wide range of target outputs. Indeed, for some target outputs (_e.g._ plaintext)
   it may not even be possible to accurately render most formulas.

I have been contemplating possible solutions and I see several possible ways forward...

### Approach 1: Require any formula support to be via extensions

The simplest solution is to ***not*** add `=formula` and `F<>`,
but to relegate any formula support to custom extensions.
That is, any RakuDoc renderer could elect to implement an extended syntax
(say, `=Formula` and `𝔽()`), but no other renderer would be required to
support that extension.

And that’s the problem: any RakuDoc document that used the extension syntax
would immediately cease to be portable. Moreover, there is no guarantee that
different renderers might not implement incompatible versions of `=formula`
(for example, one that requires LaTeX markup syntax; the other using AsciiMath)
or might define different inline markup instructions (`𝐅<>`, `𝐹<>`, `𝔉<>`, or `𝖥<>`).

In light of those issues, it seems that, if there were some way to define
a standard `=formula` and `F<>` syntax that doesn’t unduly restrict either
end-users or implementors, then we should seriously consider doing so.
The following section explores that possibiity.

### Approach 2: Make formula syntax required, but make formula rendering optional

If Rakudoc were to specify a standard `=formula` block and `F<>` instruction
then we need to address the two significant problems mentioned earlier.
We need to decide which notation(s) these constructs should support
and we need a way for formulas to be rendered in all output formats
without driving either end-users or implementors to despair.

The first issue is – comparatively – the easier to resolve. Having spent
some considerable time now researching the various options, I strongly concur
with @zag that the obvious candidate is the [LaTeX mathematical syntax](https://en.wikibooks.org/wiki/LaTeX/Mathematics).
TeX/LaTeX is by far the most commonly used mathematical markup notation
across a wide range of documentation systems.

Moreover, LaTeX mathematics is trivially easy to render to a wide range of output formats.
The syntax can be rendered in all HTML/CSS environments by using the highly regarded
Open Source [MathJax library](https://www.mathjax.org/). LaTeX notation is also simple to convert to many Markdown variants
because most Markdown dialects that support formulas do so by allowing embedded LaTeX.
And, of course, LaTeX mathematical markup would be relatively easy to convert
to the many other output formats that LaTeX itself targets.
_(Note, however, that I am not volunteering to do any of this myself! ;-)_

Therefore, I agree with @zag that LaTeX notation (including the extensions specified
in the [AMSMath package](https://en.wikipedia.org/wiki/AMS-LaTeX)) is the right choice for any `=formula`/`F<>` feature.

The question then is: how to enable implementors to cope with rendering this complex sublanguage.
And I think the answer is: ***by not actually requiring them to do so.***

That is, I think that, if we add a formula feature, we should explicitly document that
implementors of renderers are ***not*** required to render the contents of these instructions.
We should state clearly that it is perfectly acceptable for a renderer to render the contents
of a `=formula` or `F<>` in some other way than as a fully realized mathematical equation.

For example, we should document that the following two formulas:
```rakudoc
We will use the identity: F<\sum \frac{1}{n^{2}} = \frac{\pi^{2}}{6}>

...where the value of pi can be inferred from Euler’s Identity:

=formula e^{i\pi}+1=0
```

...may either be rendered “accurately”:

> We will use the identity: $\sum \frac{1}{n^{2}} = \frac{\pi^{2}}{6}$
>
> ...where the value of pi can be inferred from Euler’s Identity:
>
> $e^{i\pi}+1=0$

...or may be converted to a suitable Unicode approximation:

> We will use the identity: ∑ 1/n² = 𝜋²/6
>
> ...where the value of pi can be inferred from Euler’s Identity:
>
> eⁱᐢ + 1 = 0

...or may even left as raw LaTeX (perhaps with some kind of visual marker indicating
that it is unprocessed):

> We will use the identity: _`\sum \frac{1}{n^{2}} = \frac{\pi^{2}}{6}`_
>
> ...where the value of pi can be inferred from Euler’s Identity:
>
> _`e^{i\pi}+1=0`_

More importantly, we should allow both `=formula` and `F<>` to take explicit
ALT texts, so that the end-user can decide how their formula should be rendered 
in cases where the renderer cannot handle the specification.

That is, the `=formula` block should accept an `:alt` metaoption,
and the syntax for the `F<>` instruction should allow both <code>F&lt;<em>FORMULA</em>&gt;</code> and <code>F&lt;<em>ALT</em> | <em>FORMULA</em>&gt;</code>,
so that the end-user can supply a suitable explicit alternative rendering
to renderers that cannot handle the full formula syntax:

```rakudoc
We will use the identity: F<∑ 1/n² = 𝜋²/6 | \sum \frac{1}{n^{2}} = \frac{\pi^{2}}{6}>
                            ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

...where the value of pi can be inferred from Euler’s Identity:

=for formula  :alt< eH<iπ> + 1 = 0 >
e^{i\pi}+1=0  ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
```

Providing formulas with user-configurable ALT texts would greatly increase the portability
of the mechanism. Users would be able to rely on getting “accurate” representations under
those renderers that fully support formulas, and would still be able to fall back on
a wide range of reasonable alternatives under those renderers that don’t:

| Fall back on | Example |
| :----------- | :------ |
| Plaintext | `F< Euler's Identity                                    \| e^{i\pi}+1=0 >` |
| RakuDoc   | `F< eH<iπ> + 1 = 0                                      \| e^{i\pi}+1=0 >` |
| Unicode   | `F< eⁱᐢ + 1 = 0                                         \| e^{i\pi}+1=0 >` |
| Image     | `F< P<file:EulerID.jpg>                                 \| e^{i\pi}+1=0 >` |
| Link      | `F< L<https://en.wikipedia.org/wiki/Euler%27s_identity> \| e^{i\pi}+1=0 >` |

Moreover, if ALT texts were rendered like normal inline text (_i.e._ if they honoured
embedded formatting codes), then user’s could even ***stack*** their fallbacks.
For example, they could try for an “accurate” rendering of a formula,
but fall back on the placement of a pre-rendered image, or (failing to find that)
fall back again to a RakuDoc representation with an outgoing link:

```rakudoc
We will use: F<
                 P<
                     L< eH<iπ> + 1 = 0
                      | https://en.wikipedia.org/wiki/Euler%27s_identity
                      >
                  | file:EulerID.jpg
                  >
              | e^{i\pi}+1=0
              >
```

Note that allowing ALT fallbacks would also significant reduce the load on implementors.
Implementors would be completely free to delay – or completely reject – implementing
LaTeX-based formulas, without stranding their end-users with no means of producing
reasonable formula output. 

And implementations would still be considered fully compliant with the official specification,
even if they ***never*** chose to implement full formula support.

#### Metadata options for `=formula` blocks and `F<>` codes

The `F<>` instruction would only support one option: an ALT text 
in the usual before-the-bar location: <code>F&lt;<em>ALT</em> | <em>FORMULA</em>&gt;</code>
(as described above).

However, `=formula` blocks would allow any of the following metaoptions:

- `:alt` - Provide an ALT text, to be rendered instead if the formula itself cannot be rendered
- `:caption` - Associate a caption with the formula
- `:id` - Specify a unique ID for the formula block (typically, to be used as a link target)
- `:toc` - Add the formula to the Table of Contents

### Conclusion

Note that I am not saying that we ***must*** add a standard `=formula`/`F<>` mechanism.
I am not even saying that we ***should*** add a standard `=formula`/`F<>` mechanism.
I am only saying that we ***could*** add a standard `=formula`/`F<>` mechanism in a way that:

* avoids the creation of multiple inconsistent language extensions,
* provides better portability for all RakuDoc documents,
* provides some degree of user-configurable rendering of formulas,
* does not place an undue burden on implementors (unless they choose that burden)
* can in many instances leverage existing tools and libraries for an implemention

For all these reasons I would like to submit the above suggestions
as a starting point for possible discussion.

**Comment by finanalyst** [comment]
@thoughtstream @zag @lizmat 
- I'm happy with having a `=formula / F<>` block in principle; my concern mirrored @thoughtstream regarding different syntaxes.
- I already have Latex formula for my `Raku::Pod::Render` renderer, so it is quite easy to implement.
- If other formula syntax is desired, then it could be implemented using the Custom block / custom markup
- the idea of optional rendering is consistent with other parts of the RakuDoc v2 specification. When a Custom block is encountered, and the renderer does not 'know' how to render it, the specification is that the contents are rendered verbatim.

@thoughtstream you said:
> And that’s the problem: any RakuDoc document that used the extension syntax
would immediately cease to be portable. Moreover, there is no guarantee that
different renderers might not implement incompatible versions

This is a more general problem that we will face because we allow customisation and we explicitly expect there to be multiple renderers.

My thought on this is that whenever a custom block or format code, there **must** be a `DOC use module-name` statement in the source file, so that there is some way for an author to fix the rendering.

**Comment by thoughtstream** [comment]
> My thought on this is that whenever a custom block or format code, there **must** be a `DOC use module-name` statement in the source file, so that there is some way for an author to fix the rendering.

I'm not sure what _"must"_ implies there. Do you mean that it's a fatal error if nothing has been `DOC use`'d 
to handle the custom element? Or does a missing custom handler just generate a warning?

I feel that it would enough that, when a render encounters an unknown custom element,
for the renderer to render the contents verbatim and also to issue a warning...perhaps as 
a note at the end of the output.

**Comment by finanalyst** [comment]
@thoughtstream I was thinking more that a custom block / code **without** a
DOC use would trigger some error.
Perhaps we should also specify how errors are signalled. Adding a warning
to the end of output seems good

**Comment by thoughtstream** [comment]
> I was thinking more that a custom block / code **without** a DOC use would trigger some error. 

I think that encountering a custom block/code ***that the renderer doesn't know how to handle***
should trigger an error, whether there is a `DOC use` or not.

I can imagine some renderers being able to intrinsically handle some custom blocks or codes
_(as, I believe, your own renderer already does with Font Awesome markup)._ In such cases,
no `DOC use` would be required, so the absence of a `DOC use` should not trigger an error.

Contrariwise, I can also imagine someone `DOC use`-ing a module that they ***believe*** is going
to enable a particular custom block or code, but which doesn't actually do so. In that case, 
encountering a custom block/code should still trigger a warning, even though there is 
a least one `DOC use` in the source.

On the gripping hand, some renderers may not implement optional built-in features (such a formulas)
so the use of those features in a document might still trigger a renderer warning/error, even though 
no `DOC use` is actually required in that case.

The bottom line then is that being asked to render an unknown block/code (whether custom or built-in)
should always trigger some form of warning, regardless of the presence/absence of a `DOC use`.

However...I do agree that the error message for an unhandled custom block/code should mention 
the likely need for a `DOC use`:
```error
    Unknown block encountered, starting at line 42: =begin Css 
    (Did you need a load a handler for this block type via a "DOC use" statement?)
```

> Perhaps we should also specify how errors are signalled. Adding a warning to the end of output seems good.

I agree we should mandate that some kind of warning must be given 
(unless specifically switched off by the user during rendering). 

But I think we should only ***suggest*** a range of ways in which errors may be signalled.
I don't believe we should mandate any one particular way in which errors must be signalled, 
because the range of rendering environments, and of target output formats, is simply too broad 
for there to be a single optimal error-signalling approach for all cases.

We could specify that that rendering errors – including unknown block/code types, as well as 
the use of unimplemented built-ins – must be signalled in some way, unless such warnings 
have been explicitly silenced. Then we could suggest the following signalling mechanisms 
as being acceptable approaches to fulfil this requirement:
* writing error messages to STDERR
* writing error messages to a log file
* appending error messages to the end of the rendered output in a distinctive style that indicates they are errors
* rendering unhandled blocks or codes inline (in a distinctive style) and providing the associated error message 
   in a pop-up that activates on hover or mouse-click
* _any other suitable approaches that we can think of_

**Comment by finanalyst** [comment]
Issue on errors addressed, issue on Formula when I next have some time.

**Comment by zag** [comment]
@thoughtstream , 
the ALT failover solution looks really elegant to me, especially with pre-rendered images and the ability to stack their fallbacks!
thank you

**Comment by thoughtstream** [comment]
> Suppose we consider that each of A, E, and P have a default ALT, which is the error message, 
> and that providing an explicit ALT over-rides the default?

My idea was that, if the user explicitly specifies a display text on an `A<>`, `E<>`, or `P<>`
then that represents a default rendering, which is to be used ***instead*** of generating an error message.

In other words, the document writer can choose to explicitly provide a fallback to be rendered
and thereby override the _"missing resource"_ error that would otherwise be generated.

In other words:
| Markup | Failure rendered as... | Error reported? |
| :----- | :--------------------- | :-------------: |
| `A<This is copyrighted \| COPYRIGHT>` | This is copyrighted | no |
| `A<COPYRIGHT>` | ***COPYRIGHT*** | yes |
| `E<left double-angle character \| laquo>` | left double-angle character | no |
| `E<laquo>` | ***&lt;laquo&gt;*** | yes |
| `P<NO WARRANTY. \| http://disclaimer.com/std.txt>` | [NO WARRANTY](http://www.disclaimer.com/std.txt) | no |
| `P<http://disclaimer.com/std.txt>` | ***[http://disclaimer.com/std.txt](http://disclaimer.com/std.txt)*** | yes |

**Comment by finanalyst** [comment]
@thoughtstream For clarity, that was my idea too. The PR makes it clear.
I think this issue can be closed as completed.

**Comment by thoughtstream** [comment]
> I think this issue can be closed as completed.

Agreed.
