### ISSUE TITLE
scope and forward references

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#13]
@thoughtstream I'm working on rendering `=config`, `=alias`, and `=place`. There are some parts of the specification I think may need clarifying. 
`=config` and `=alias` are specified as *block scoped*, I am calling this 'scope'.
`=place` / `P<>` explicitly allows for incorporation of data that may not yet be parsed by the renderer, (eg. toc:). I am calling this a 'forward reference'
# config
Although `=config` and `=alias` are specified as block scoped, does this mean in Raku terms
1. scoped as lexical variable, meaning starting at the declaration and ending at the end of scope, or
2. scoped as a sub routine, meaning it can be declared anywhere within a scope but be available throughout the scope.

For `=config`, I think it should definitely be the first, so if we have
```
=begin rakudoc
=comment this is the beginning of the scope

=head1 some title

this is text

=config head1 :!toc
=head1 some other title

more text
=end rakudoc
```
The `=config` directive only applies to **some other title** and NOT to **some title**.
I think this makes sense and I cannot imagine how having `=config` having some backward effect would be intuitive or useful.

# alias
Now consider `=alias`. Again, it is specified as 'block scoped'. However, I could imagine that there ***might*** be a use for an `A<AUTH>` to refer to an `=alias` block that is defined at the end of a section.
In other words, this is *block scoped* like a subroutine.

However, a consequence would mean that `A<>` ( like `P<>` ) would allow for forward references, but only if its in the  scope. An extreme example would be
```
=begin rakudoc

We are grateful to A<AUTH> for their aid.

=head how to be calm

text

=begin section

=alias AUTH  Evil Troll, and D. Bad Politician

more text

The truth is that people like A<AUTH> are narcissists.

=end section

So we are thankful A<AUTH> for being.

=alias AUTH A.Author, and B.Good

=end rakudoc
```
Since the *Evil Troll ...* is in another block scope, the first and third `A<>` both refer to *A. Author ...*
But to be honest, this is confusing, and it could be argued that the first and second 'A<>' refer to *Evil Troll ...*.

From the point of view of keeping things simple (both for an implementer, but also for the document writer), I propose that the scoping of `A<>` is the same as for `=config`. This would mean that the idea of 'block scope' for a RakuDoc source is always an analogy of a 'lexical variable'. 

There are two consequences of this simpler interpretation:
1. forward references and block scope are orthogonal, in that a scoped object cannot have a forward reference
2.  if an `A<some id>` refers to an `=alias some_id` that is specified later, it would not be rendered.

Another possibility is to relax the scoping requirement on `=alias` and allow forward references.

**Comment by thoughtstream** [comment]
> ### config
>     1. scoped as lexical variable, meaning starting at the declaration and ending at the end of scope, or
>     2. scoped as a sub routine, meaning it can be declared anywhere within a scope but be available throughout the scope.
>
> For `=config`, I think it should definitely be the first,

I strongly agree. As you say, that's what makes sense, and that was certainly my intention, 
even if I didn't specify it explicitly.

I think it would be enough to make the following change to the specification:
```diff
- B<=config> specifies default options to be applied to specific types of blocks or markup instructions.
+ B<=config> specifies default options to be applied to specific types of blocks or markup instructions 
+ within the current lexical block-scope. These default options apply from immediately after 
+ the C<=config> directive up to the end of the innermost surrounding block.
```


> ### alias
> From the point of view of keeping things simple (both for an implementer, but also for the document writer), I propose that the scoping of `A<>` is the same as for `=config`. This would mean that the idea of 'block scope' for a RakuDoc source is always an analogy of a 'lexical variable'.

Again, I strongly agree. This was my intent for all scoped constructs: that they take effect from the point of definition
to the end of the innermost surrounding block scope (just like a lexical variable).

I think it would be enough to make the following change to the specification:
```diff
- An C<=alias> is scoped to the surrounding RakuDoc block.
+ An C<=alias> is lexically scoped from immediately after its declaration 
+ up to the end of the innermost surrounding RakuDoc block.
```


> There are two consequences of this simpler interpretation:
> 1. forward references and block scope are orthogonal, in that a scoped object cannot have a forward reference

Agreed.

> 2. if an `A<some id>` refers to an `=alias some_id` that is specified later, it would not be rendered.

...and would cause an error to be reported.

**Comment by finanalyst** [comment]
The S26 said 'lexically scoped' but @liz suggested 'block scoped' to avoid
implicitly linking RakuDoc with Raku where lexically scoped' has more
assumptions. Eg - I think - subroutines can be lexically scoped'.

**Comment by thoughtstream** [comment]
I fully understand @lizmat's desire to avoid _"lexical"_.

In which case we could update the two sections like so:

```diff
- B<=config> specifies default options to be applied to specific types of blocks or markup instructions.
+ B<=config> specifies default options to be applied to specific types of blocks or markup instructions 
+ within the remainder of the current block-scope. These default options apply from immediately after 
+ the C<=config> directive up to the end of the innermost surrounding block.
```

...and:

```diff
- An C<=alias> is scoped to the surrounding RakuDoc block.
+ An C<=alias> is scoped from immediately after its declaration 
+ up to the end of the innermost surrounding RakuDoc block.
```

**Comment by finanalyst** [comment]
++ I'll update in a couple of days and include new Formula as well.

Also add something about error messages.

Hopefully we can wrap this stage up by Dec 1

**Comment by finanalyst** [comment]
closing as completed
