### ISSUE TITLE
Declaring the revision process over

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#18]
After finalising ideas prompted by @zag's suggestions, which included a more generic placement block, display texts for codes that can fail, and a new Formula block, it seems to me that the specification process for the language has come to a natural end.

The issue of signaling where customisations are to be found remains open, but can be considered an implementation detail at this time - IMHO.

Unless a significant new change is identified, I suggest the specification here can be moved to the Raku Steering Council for adoption.

@thoughtstream @Raku/docteam @Raku/core Any objections?

**Comment by thoughtstream** [comment]
There remains the issue of @zag's `:checkbox` proposal, 
which I'll address in [the separate thread](https://github.com/Raku/RakuDoc-GAMMA/issues/5#issuecomment-1847447463).

I don't think we should pursue the more extensive "selector"  mechanism
that @zag also proposed, as it seems to be tied closely to his Podlite design, 
which has some fundamental differences from our RakuDoc approach.

As for @zag's <code>W&lt;<em>URI</em>&gt;</code> proposal, I'm still not sure I entirely understand it, 
but it does already seem to be covered by: <code>N&lt;P&lt;<em>URI</em>&gt;&gt;</code>

So, apart from `:checkbox`, yes I agree that our redesign process has reached a natural conclusion
and _(assuming we can quickly address the above issue)_ should be moved to the RSC for approval.

**Comment by finanalyst** [comment]
process completed. normal revision.
