### ISSUE TITLE
Tests for RakuDoc v2

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#21]
1. While the RakuDoc document in this repo has examples of many RakuDoc v2 instructions, it does not test all the components. In addition, since the purpose of the file is to document and specify, there is a lot of text that is not needed for purely testing purposes.
1. Since RakuDoc is declarative and is neutral to the output, but at the same time a rendered text is format specific, how can a Renderer be tested in a standard way?

# Compliance tests
It would be useful to have a test document, or set of test documents, which a renderer should render without a failure, or if failure modes are being tested, a set of expected responses.

@thoughtstream @zag  thoughts?

**Comment by thoughtstream** [comment]
I wholeheartedly agree that it would be useful to have one or more documents
that cover every variation of every feature of RakuDoc. It might be useful 
to autogenerate these test documents from comprehensive lists of directives,
blocks, and inline markup codes. Such lists might even perhaps be extracted 
from the tables at the end of the specification document itself.

As for standardized testing, I have absolutely no idea 
how that might be reasonably accomplished. Sorry. :-(

**Comment by finanalyst** [comment]
@thoughtstream @Raku/core There is a new season of Google Summer of Code. The project categories can include short projects. How about a project that has the aim of generating test rakudoc that as suggested by @thoughtstream ? We would need a project outline and mentor. Any takers?

**Comment by finanalyst** [comment]
I have developed a set of test templates that turn the each block into string with config parameters, Then 'real' output templates would place those parameters into text strings or HTML containers, attributes etc.
Closing as resolved
