### ISSUE TITLE
syntax of `toc:` schema

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#25]
@thoughtstream Implementing `=place` in Rakudo AST and RakuDoc-Render yields an anomaly:
schemas that are used in `=place` and `P<>` all have the form `\w+:\S+?` except for (I think) `toc:` and `index:`.
eg: 
```
P<https://nonsense.org/disclaimer>
or 
=place rakudoc:App::Rak
but 
=place toc: :toc<Table of contents>
```

Optionally we can specify, eg. `toc:1,2` to get only first two levels of *toc*.

I suggest mandating schemas `toc:` and `index:` as `toc:*` and `index:*` to make the parsing consistent. 
The use of `*` to mean **everything** seems consistent with `*` as **whatever**.
@lizmat Is this reasonable?

**Comment by lizmat** [comment]
The question is really: is `toc:` a URI or not?

If it is, or we would want to simply allow `toc:` as a value in `=place`, then a simple change in the grammar would be sufficient (basically a `\S+` -> `\S*`)

**Comment by finanalyst** [comment]
@lizmat suppose
```
=place rakudoc: App::Rak :caption<awesome Raku utility>
```
since only optional metadata can appear after the URI , this might be a valid place directive.

**Comment by lizmat** [comment]
@finanalyst Do you really mean `rakudoc: App::Rak` (with a space between) or do you mean `rakudoc:App::Rak` ??  The former wouldn't work, even if `rakudoc:` would be a `URI`, because the string `App::Rak` is not a config specification.  The config specification needs to go before any text.

**Comment by finanalyst** [comment]
@lizmat I'm wondering out loud, and probably not quite understanding everything. My thought was that if the regex was `\w+:\S*` then  it would allow `toc:     ` but it would also allow `rakudoc:     App::Rak`. I am placing many spaces here for clarity because sometimes a single space could be a typo that's difficult to pick up when debugging.
But I think you are right that `rakudoc:App::Rak` is a URI and (maybe) a correct URI would not have an embedded space

**Comment by lizmat** [comment]
@finanalyst If spaces would be allowed, how would it check when the config begins?  By checking for `:` ?  But what if there would be no config?

**Comment by thoughtstream** [comment]
My view is that the schemas should be required to match `/toc:\S+/` and `/index:\S+/`
and, as @finanalyst suggested, that the following forms should be allowed:

```raku
    toc:*         # Means: all TOC levels
    toc:1,2       # Means: only specified TOC levels

    index:*       # Means: all index levels
    index:1,2     # Means: only specified index levels
```

but, also as @lizmat  suggested, that the scheme should under no circumstances 
be allowed to have whitespace in it.

Damian

**Comment by finanalyst** [comment]
@lizmat @thoughtstream So it is possible to have bare `toc:` and `index:` [as well as `toc:1,2` etc] , otherwise a URI is `\w+:\S+`  ?

**Comment by lizmat** [comment]
I think @thoughtstream meant that any schema consisting of `\w+:` would *not* be allowed.  Now. I'm not sure whether `toc:` and `index:` should be special cased.

**Comment by finanalyst** [comment]
@lizmat My bad. I just re-read this issue thread and missed Damian's last comment. It seems he agrees with my initial suggestion that only `toc:*` &  `index:*` should be allowed.
This means that bare `toc:*` &c creates a parse error, and RakuDoc v2 spec needs a minor change.

**Comment by thoughtstream** [comment]
Just to clarify: I would prefer if we required `toc:*` and `index:*`,
rather than allowing bare `toc:` and `index:`

I think the consistency of requiring a valid (_i.e._ non-null) URL form for every schema
is worth the slight inconvenience of users having to add the asterisk.

Besides, I find a construction like:
```rakudoc
=place toc:  :toc<Table of contents>
```
confusing, and less easily understood than:
```rakudoc
=place toc:*  :toc<Table of contents>
```
_(The symmetry of `toc: :toc` is just too distracting! ;-)_

**Comment by finanalyst** [comment]
My thoughts exactly

**Comment by finanalyst** [comment]
closing as resolved
