### ISSUE TITLE
Creating a Proving file

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#34]
For my own testing, I am creating a RakuDoc source called **rakudociem-ipsum.rakudoc** (a sort of take on lorem ipsum) to contain as many RakuDoc components as possible, in various combinations.

The aim is to prove the renderers (generic, text, HTML, MarkDown) that I am writing, and also to give me a feel about how the rendered versions will look.

It occurred to me that it might be useful to include such a source in this repo.

@thoughtstream  @liz Any thoughts?

**Comment by lizmat** [comment]
Shouldn't such a file be part of the test suite?  And thus be part of the repo?

**Comment by thoughtstream** [comment]
_Existimo optimum esse, si documentum quam plenissimum practicabile praebemus._

(I think it would be great if we provided an _as-near-to-exhaustive-as-practicable_ test document. :-)

**Comment by finanalyst** [comment]
I have just written the first draft, but the compiler is choking on it - probably my mistake. I'll add it to the repo once I've got them fixed.
However, its quite tedious getting all the corner cases in. So, it will need TLC.

**Comment by finanalyst** [comment]
@thoughtstream @lizmat Here is a first draft of a proving file.
There is one passage that has been commented out, namely `=for formula ...` as described in #33 
The file will compile with the most recent version of raku
```
$ raku -v
Welcome to Rakudo™ v2024.05-18-g587cd72f6.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.05.
$ RAKUDO_RAKUAST=1 raku -c rakudociem-ipsum.rakudoc 
Syntax OK
```

**Comment by thoughtstream** [comment]
Excellent work, @finanalyst.

**Comment by finanalyst** [comment]
@thoughtstream @lizmat @zag 
I have just added some more test files for the compliance renderer. These are intended to be short files in different formats, text, image, JSON, RakuDoc, as specified in the RakuDoc specification. 
The idea is that they can be accessed by a `P<>` or `=place` command.

Any objection?

Should they be in the root directory or a subdirectory?

I'll be rewriting the README in due course into a RakuDoc source, then render it to md.

**Comment by thoughtstream** [comment]
> Any objection?

None here.

> Should they be in the root directory or a subdirectory?

In a subdirectory, I think.

**Comment by finanalyst** [comment]
closing issue as resolved
