### ISSUE TITLE
Can we have .rakudoc files be pure, clean RakuDoc?

### ISSUE THREAD

**Issue by patrickbkr** [Raku/RakuDoc-GAMMA#48]
The [spec currently says](https://github.com/Raku/RakuDoc-GAMMA/blob/main/rakudoc_draft_3.rakudoc#L113C1-L113C68):

    A file with mainly RakuDoc source has a file extension B<.rakudoc>.

Can we change that to

    A file with exclusively RakuDoc source has a file extension B<.rakudoc>.

This one change would effectively introduce the concept of clean RakuDoc that contains no ambient code. We could then have a pure RakuDoc parser that inherits none of the issues that a Raku parser has (being unsafe by potentially running BEGIN code), and could be a looot simpler as Raku is a huge language, while RakuDoc isn't. Having such a parser would directly unblock rendering .rakudoc documents on GitHub, GitLab or anywhere else on the web.

**Comment by thoughtstream** [comment]
Thanks for bringing this issue up, @patrickbkr.

Actually, I think it indicates that the sentence is the wrong way round,
...and that changing it from "mainly" to "exclusively" won't actually fix 
the issue you're addressing.

Hence, I'd suggest we change the sentence to:
```rakudoc
The file extension for a file containing RakuDoc source is B<.rakudoc>.
```
...to make it clear that all we're specifying here is the lower-casing of the file extension.

To address your concern and your desire for a guarantee of "pure" RakuDoc, I think
we need to add something else. I think we need to specify that any file with the
extension `.rakudoc` ***must*** be treated as if it has an implicit `=begin rakudoc`...`=end rakudoc`
around its contents. That way, every `.rakudoc` file is automatically guaranteed to be "pure,"
even if its contents don't appear to be composed exclusively of RakuDoc constructs.

Note that we [currently specify](https://github.com/Raku/RakuDoc-GAMMA/blob/b8372e27744a34df2d0de08a8ab988fd142e92fb/rakudoc_draft_3.rakudoc#L849C1-L850C32) that files intended to be "pure" RakuDoc should be entirely
enclosed in an explicit `=begin rakudoc`...`=end rakudoc` pair. 

I'm suggesting that we extend that specification as follows:
```diff
@@ -849,6 +849,11 @@
 Files that are intended to contain text-oriented documentation alone should be entirely
 enclosed in a C<rakudoc> block.
 
+However, files whose filename ends in a C<.rakudoc> extension are always presumed
+to contain only text-oriented documentation, and any renderer must always treat
+the file's contents as being enclosed in an implicit C<=begin rakudoc>...C<=end rakudoc>,
+unless those contents are already explicitly enclosed in a C<rakudoc> block.
+
 Historically the name C<pod> was used for this functionality.
 For compatibility it will still be possible to use the name C<pod>
 instead of C<rakudoc> in the foreseeable future.  Note however

```

**Comment by patrickbkr** [comment]
I agree. Let's have this. What's the process? Just creating a PR? Should I?

**Comment by thoughtstream** [comment]
By all means create a PR, @patrickbkr.

Of course, I'd still like to hear from @finanalyst and @lizmat on this issue
before we make any final decision on the idea.

**Comment by finanalyst** [comment]
@thoughtstream @patrickbkr @lizmat Sorry to be SO late in responding. 

Liz and I had already discussed the idea that a `.rakudoc` file would imply an enclosing `=begin rakudoc/=end rakudoc`. So in principle, I'm in favour.

FYI All Raku documentation files are `.rakudoc` and all of them have an explicit **rakudoc** block including several metadata options that are used to order the files within the website.

I'll merge the PR.
