### ISSUE TITLE
Embedded markup in =alias

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#53]
@thoughtstream Flaw #5 you picked up was generated by the following RakuDoc 
@lizmat Please comment
```
=alias PROGNAME    Earl Irradiatem Evermore
=alias VENDOR      4D Kingdoms
=alias TERMS_URLS  =item L<http://www.4dk.com/eie>
=                  =item L<http://www.4dk.co.uk/eie.io/>
=                  =item L<http://www.fordecay.ch/canttouchthis>

The use of A<PROGNAME> is subject to the terms and conditions
laid out by A<VENDOR>, as specified at:
    A<TERMS_URLS>
```
The problem arises from embedding multiple =item blocks in the alias value part.
The parser (as can be seen below) is explicitly treating whatever follows the NAME_PART as a paragraph. But the syntax above is treating the remaining part of the alias as a sort of =section.  Since the `A<>` is normally inserted inline, treating it as a series of blocks would cause problems with new lines and indenting.

Would be the following be valid?
```
=alias CODE_SNIPPET =for code
=     my $var = 2;
=     say $var;
```

I think that there may need to be some extra information about what may follow the NAME_PART of an alias.

The current parsing into the AST is not simple. I'll provide the AST for the alias and for the same set of blocks in normal RakuDoc. Here is the AST just for the 3rd `=alias` block (note how the `=item` has been treated as a string):
```
      RakuAST::Doc::Block.new(
        type       => "alias",
        directive  => True,
        paragraphs => (
          "VENDOR",
          "4D Kingdoms",
        )
      ),
      RakuAST::Doc::Block.new(
        type       => "alias",
        directive  => True,
        paragraphs => (
          "TERMS_URLS",
          RakuAST::Doc::Paragraph.new(
            "=item ",
            RakuAST::Doc::Markup.new(
              letter => "L",
              opener => "<",
              closer => ">",
              atoms  => (
                "http://www.4dk.com/eie",
              )
            ),
            "\n=item ",
            RakuAST::Doc::Markup.new(
              letter => "L",
              opener => "<",
              closer => ">",
              atoms  => (
                "http://www.4dk.co.uk/eie.io/",
              )
            ),
            "\n=item ",
            RakuAST::Doc::Markup.new(
              letter => "L",
              opener => "<",
              closer => ">",
              atoms  => (
                "http://www.fordecay.ch/canttouchthis",
              )
            )
          ),
        )
      )
```
For comparison, here is a normal RakuDoc sequence and the AST it generates.
```
=item L<http://www.4dk.com/eie>
=item L<http://www.4dk.co.uk/eie.io/>
=item L<http://www.fordecay.ch/canttouchthis>
```
AST (Note each =item has its own block object)
```      RakuAST::Doc::Block.new(
        type        => "item",
        abbreviated => True,
        paragraphs  => (
          RakuAST::Doc::Paragraph.new(
            RakuAST::Doc::Markup.new(
              letter => "L",
              opener => "<",
              closer => ">",
              atoms  => (
                "http://www.4dk.co.uk/eie.io/",
              )
            ),
            "\n"
          ),
        )
      ),
      RakuAST::Doc::Block.new(
        type        => "item",
        abbreviated => True,
        paragraphs  => (
          RakuAST::Doc::Paragraph.new(
            RakuAST::Doc::Markup.new(
              letter => "L",
              opener => "<",
              closer => ">",
              atoms  => (
                "http://www.fordecay.ch/canttouchthis",
              )
            ),
            "\n\n"
          ),
        )
      ),
      RakuAST::Doc::Block.new(
        type       => "alias",
        directive  => True,
        paragraphs => (
          "TERMS_URLS",
          RakuAST::Doc::Paragraph.new(
            "=begin section\n=item ",
            RakuAST::Doc::Markup.new(
              letter => "L",
              opener => "<",
              closer => ">",
              atoms  => (
                "http://www.4dk.com/eie",
              )
            ),
            "\n=item ",
            RakuAST::Doc::Markup.new(
              letter => "L",
              opener => "<",
              closer => ">",
              atoms  => (
                "http://www.4dk.co.uk/eie.io/",
              )
            ),
            "\n=item ",
            RakuAST::Doc::Markup.new(
              letter => "L",
              opener => "<",
              closer => ">",
              atoms  => (
                "http://www.fordecay.ch/canttouchthis",
              )
            ),
            "\n=end section"
          ),
        )
      ),
    )
  )

```

**Comment by thoughtstream** [comment]
> The problem arises from embedding multiple =item blocks in the alias value part.
> The parser (as can be seen below) is explicitly treating whatever follows the NAME_PART as a
> paragraph. But the syntax above is treating the remaining part of the alias as a sort of `=section`.

Yes. My intent was that everything in an `=alias` after the _NAME_PART_ should be treated as raw
RakuDoc source that would be textually substituted in place of any corresponding `A<NAME_PART>`.
In other words, an `=alias` acts like the definition of a source-code **macro**, which any subsequent
`A<>` would interpolate ***before the source is parsed***.

Of course, in hindsight that’s probably either fiendishly difficult for the parser, or simply outright impossible.

So my revised intent is that everything after the _NAME_PART_ of an `=alias` should be
parsed as an independent subdocument, using a slightly modified slang of Rakudoc
(_i.e._ using a slang in which each line except the first must begin with a `=`).

Thus I would expect that the parser would produce the following AST
when parsing the example _“TERMS_URL”_ `=alias`. Presumably, the renderer 
would subsequently put that AST into a look-up table (say: `%aliases`)
under the appropriate name. Hence, we’d get the equivalent of:

```raku
    %aliases<TERMS_URLS> = RakuAST::Doc::Block.new(
        type       => "alias",
        directive  => True,
        paragraphs => (
            "TERMS_URLS",
            RakuAST::Doc::Block.new(
                type        => "item",
                abbreviated => True,
                paragraphs  => (
                    RakuAST::Doc::Paragraph.new(
                        RakuAST::Doc::Markup.new(
                            letter => "L",
                            opener => "<",
                            closer => ">",
                            atoms  => ( "http://www.4dk.co.uk/eie.io/" )
                        )
                    ),
                )
            )
            "\n",
            RakuAST::Doc::Block.new(
                type        => "item",
                abbreviated => True,
                paragraphs  => (
                    RakuAST::Doc::Paragraph.new(
                        RakuAST::Doc::Markup.new(
                            letter => "L",
                            opener => "<",
                            closer => ">",
                            atoms  => ( "http://www.fordecay.ch/canttouchthis" )
                        )
                    )
                )
            ),
            "\n"
        )
    )
```

Thereafter, whenever the renderer receives the AST for an `A<TERMS_URLS>`, it would simply
render `$aliases<TERMS_URLS>.paragraphs.[1..*-1]` instead.


> Since the `A<>` is normally inserted inline, treating it as a series of blocks
> would cause problems with new lines and indenting.

The embedded newline(s) for an inlined `A<>` could be handled by choosing to not render the
final element of `$aliases<TERMS_URLS>.paragraphs` (because that final element would always be
a newline).

That that’s why I wrote `.[1..*-1]` rather than `.[1..*]` in the previous paragraph.
Starting at `1` skips the alias name, finishing at `*-1` skips the final newline.
For a single-line alias such as:
```rakudoc
    =alias PROGNAME    Earl Irradiatem Evermore
```
...that ensures that an interpolation such as:
```rakudoc
    The use of A<PROGNAME> is subject to the terms and conditions
```
...wouldn’t get an extraneous newline added before the _“is subject to”_.


> Would be the following be valid?
> ```
> =alias CODE_SNIPPET =for code
> =     my $var = 2;
> =     say $var;
> ```

Yes.


> I think that there may need to be some extra information about what may follow the
> _NAME_PART_ of an alias.

See above.

Though, as always, I’ll be more than happy to discuss my original intentions in greater detail,
and to help you figure out how we might achieve as many of them as possible,
without driving either @lizmat or @finanalyst insane. :-)

**Comment by finanalyst** [comment]
@thoughtstream Some new considerations:
The concerns I have with this formulation, namely the value_part is a pseudo RakuDoc code, are the effects of including other blocks in the code.
- What happens when a `=head` is included? Is the head content included multiple times in the TOC?
- What above including a custom block? 
I think my renderer can manage this. For example, I have managed to include a rakudoc source in a `=place` block', eg. see the renderering of [rakudociem-ipsum](https://finanalyst.github.io/samples_rakudociem-ipsum)
Please note how `=head` blocks for `A Ware` and `B Ware` are in the included RakuDoc source and are added to the Table of Contents of the embedding document, but at the 'wrong' header level. However, I think this can be controlled by the document author.

I am also wondering about the block/inline consequences. Currently as written, an alias is invoked with `A<>`, which is inline, and so it is embedded in a `=para` block (even if the RakuDoc souce does not state this explicitly). In order to make `D<>` work, there has to be an anchor to the paragraph, so all paragraphs have to have anchors. 

However, if `=alias` defines something that is a more complex, it will contain internal paragraphs or sections. This makes it more of a block than an inline. 

When we faced this same problem with `P<>` we added `=place` to overcome this limitation. I suppose we could do the same with `A<>` to maintain the paradigm. Or maybe, have `=place alias:XXX`, which I think might be best! 

Having said that, in which way would `=alias SYNOPSIS <some rakudoc>` differ from `=SYNOPSIS <some rakudoc>`? A semantic block can be place multiple times with eg. `=place semantic:SYNOPSIS`

Though to answer my own question: a semantic block is not affected by a `=section`, whereas an alias can changed inside a `=section` and is forgotten when the section ends.

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/485474df40 handles the innards of a `=alias` as a new `.rakudoc` document, and inserts the result at the correct place.

So:
```raku
=alias PROGNAME    Earl Irradiatem Evermore
=alias VENDOR      4D Kingdoms
=alias TERMS_URLS  =item L<http://www.4dk.com/eie>
=                  =item L<http://www.4dk.co.uk/eie.io/>
=                  =item L<http://www.fordecay.ch/canttouchthis>
```
will generate this AST:
```raku
RakuAST::StatementList.new(
  RakuAST::Doc::Block.new(
    type       => "alias",
    directive  => True,
    paragraphs => (
      "PROGNAME",
      "Earl Irradiatem Evermore\n",
    )
  ),
  RakuAST::Doc::Block.new(
    type       => "alias",
    directive  => True,
    paragraphs => (
      "VENDOR",
      "4D Kingdoms\n",
    )
  ),
  RakuAST::Doc::Block.new(
    type       => "alias",
    directive  => True,
    paragraphs => (
      "TERMS_URLS",
      RakuAST::Doc::Block.new(
        type        => "item",
        abbreviated => True,
        paragraphs  => (
          RakuAST::Doc::Paragraph.new(
            RakuAST::Doc::Markup.new(
              letter => "L",
              opener => "<",
              closer => ">",
              atoms  => (
                "http://www.4dk.com/eie",
              )
            ),
            "\n"
          ),
        )
      ),
      RakuAST::Doc::Block.new(
        type        => "item",
        abbreviated => True,
        paragraphs  => (
          RakuAST::Doc::Paragraph.new(
            RakuAST::Doc::Markup.new(
              letter => "L",
              opener => "<",
              closer => ">",
              atoms  => (
                "http://www.4dk.co.uk/eie.io/",
              )
            ),
            "\n"
          ),
        )
      ),
      RakuAST::Doc::Block.new(
        type        => "item",
        abbreviated => True,
        paragraphs  => (
          RakuAST::Doc::Paragraph.new(
            RakuAST::Doc::Markup.new(
              letter => "L",
              opener => "<",
              closer => ">",
              atoms  => (
                "http://www.fordecay.ch/canttouchthis",
              )
            ),
            "\n"
          ),
        )
      ),
    )
  )
)
```
and deparse to:
```raku
=alias PROGNAME Earl Irradiatem Evermore
=alias VENDOR 4D Kingdoms
=alias TERMS_URLS =item L<http://www.4dk.com/eie>
=                 =item L<http://www.4dk.co.uk/eie.io/>
=                 =item L<http://www.fordecay.ch/canttouchthis>
```

**Comment by thoughtstream** [comment]
Awesome work by you both, @lizmat and @finanalyst!
