### ISSUE TITLE
There is no way to apply config to implicit code

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#54]
When a text paragraph is indented, it is implicit code. The code language is Raku, which is the default for implicit code.
There is no way to apply a config statement to implicit code, eg. to change the default to RakuDoc.

I suggest defining a builtin block 'implicit-code'. This behaviour is consistent with defining a `=para` block to have the same effect as an unmarked paragraph of text. But it allows for a `=config` to be applied.
```
Here is normal text
    This is implicit code

=implicit-code This is the same as implicit code above

=para This is normal paragraph defined with a block
```

**Comment by lizmat** [comment]
Afaik an implicit code block doesn't have any config, so no `:lang<raku>`.  A renderer however may decide to assume `:lang<raku>`.

**Comment by thoughtstream** [comment]
> So an alternative to my suggestion here would be to make it explicit that any config 
> for `code` is applied to implicit code in the block scope.

This would be my strong preference. 

I always envisaged that an implicit indented block
was exactly equivalent to an explicit `code` block.

So it makes sense to me that any active `=config code`
should apply equally to all implicit code blocks as well.

If we want anything other than that, then we should probably
stop calling them _"implicit ***code*** blocks"_.

**Comment by finanalyst** [comment]
I'll raise a PR to make it explicit that `=config code` affects all implicit code within the block scope

**Comment by finanalyst** [comment]
changed with commit `804d3f4`. Closed as resolved
