### ISSUE TITLE
extension of Gamma deadline ?

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#6]
@zag @thoughtstream @lizmat 
The original deadline was Nov 1 for the Gamma process to end. The hope was that three months would be enough to gather all the ideas.
However, @zag has raised some interesting ideas that need a bit of time to work through.
So I am suggesting that we extend the deadline to 1 December, and try to get consensus on incorporating (some of) @zag suggestions into the final text by then.

**Comment by thoughtstream** [comment]
I'm fine with extending the deadline to 1 December.

Please note that I am on vacation for the next 2.5 weeks, so my response-time
will be highly variable until 18 December. I will, of course, still do my best 
to contribute to the discussions.

**Comment by finanalyst** [comment]
@thoughtstream The change that we all seem to agree with is a `=place` form to match with `P<>`. I have suggested `=place` as a directive rather than block. 

I'd prefer to wait for your feedback before changing the document. It seems to me that the idea could be taken a bit further. And I'm uncertain whether it should be a directive and not a block.

**Comment by finanalyst** [comment]
closing as completed
