### ISSUE TITLE
directives in code

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#63]
@lizmat @thoughtstream This concerns the following examples where a `=config` is used in a code block.

I opened an issue in Rakudo (#5723). However, now I think the current RakuAST parser is correct.

I am opening this issue here to verify.

Currently the following produces an expected AST and is rendered as expected, with *=config* being rendered as a string
```
=begin code
   =config item :bullet<->
   =item one
=end code
=item two
```
Here `=item two` is not affected by the config.
However, in the following, the `=config` line is missing from the rendered text, and is executed.
```
=for code
   =config item :bullet<->
   =item one

=item two
```
Here `item two` is affected by the config.

I thought at first this was a flaw in the parser. Now I am unsure. Consider the following top lines of a RakuDoc source:
```
=begin rakudoc
=TITLE Build a website from current directory
=SUBTITLE The Build component for the Elucid8 framework
=for AUTHOR :hidden
Richard Hainsworth, aka finanalyst
=for VERSION :hidden
v0.1.0
=config code :lang<text>
=begin SYNOPSIS
The component is part of the C<Elucid8> distribution and is installed
.. more lines from SYNOPSIS etc
```
Here TITLE is currently ended by SUBTITLE, `=for AUTHOR` is ended by `=for VERSION` and `=for VERSION`
is ended by `=config code :lang<text>`.

This seems reasonable. But it would not be possible if `=config` were a part of the `=for VERSION` block.

So the rule being followed by the RakuAST parser is: a `=for` block is ended by a blank line **or** a directive. I am not sure whether this was explicitly specified. But I think it is reasonable.

If a directive needs to be in a `code` block, then the block must have an explicit `=begin`/`=end`.

@thoughtstream Any thoughts. If you agree with the last assertion, then I will close the Rakudo-AST issue.

**Comment by thoughtstream** [comment]
I concur with the last assertion (and with the entire analysis).
There is no bug here in the behaviour of the parser.

Every extended block and every abbreviated block always 
terminates immediately at the next blank line ***or directive.***

So a directive can only be placed as content inside a `code` block
when the `code` block is in the delimited form.

**Comment by finanalyst** [comment]
Closing as resolved
